duracion_index:
    path:     /
    defaults: { _controller: "FCOMIcomBundle:Duracion:index" }
    methods:  GET

duracion_show:
    path:     /{id}/show
    defaults: { _controller: "FCOMIcomBundle:Duracion:show" }
    methods:  GET

duracion_new:
    path:     /new
    defaults: { _controller: "FCOMIcomBundle:Duracion:new" }
    methods:  [GET, POST]

duracion_edit:
    path:     /{id}/edit
    defaults: { _controller: "FCOMIcomBundle:Duracion:edit" }
    methods:  [GET, POST]

duracion_delete:
    path:     /{id}/delete
    defaults: { _controller: "FCOMIcomBundle:Duracion:delete" }
    methods:  DELETE
