<?php

namespace FCOM\IcomBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * relacion_tematica_intervaloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class intervaloRepository extends EntityRepository
{
}
