<?php

namespace FCOM\IcomBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MensajesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajesRepository extends EntityRepository
{
}
