<?php

namespace FCOM\IcomBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Relacion_autor_intervaloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Relacion_autor_intervaloRepository extends EntityRepository
{
}
