<?php

namespace FCOM\IcomBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TematicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TematicaRepository extends EntityRepository
{
}
